name: a2c
class_name: A2C

# Training parameters
learning_rate: 0.0007
n_steps: 5
gamma: 0.99
gae_lambda: 1.0
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
normalize_advantage: false

# Network architecture
policy_hidden_dims: [64, 64]
value_hidden_dims: [64, 64]
activation: relu
shared_backbone: true

# Optimization
optimizer: rmsprop
optimizer_params:
  alpha: 0.99
  eps: 1e-5
  weight_decay: 0

# Learning rate scheduler
scheduler: step
scheduler_params:
  step_size: 100
  gamma: 0.9