name: cnn
type: cnn
backbone: custom
channels: [32, 64, 64]
kernel_sizes: [8, 4, 3]
strides: [4, 2, 1]
padding: [0, 0, 0]
pool_type: null
flatten_dim: 3136
hidden_dims: [512]
activation: relu
dropout: 0.0
batch_norm: true